# Generated by Django 4.1.2 on 2022-10-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_username_registerpg_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookenevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('stime', models.TimeField()),
                ('etime', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('food', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Registerpg',
        ),
    ]
