# Generated by Django 4.1.2 on 2022-11-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookenevent_delete_registerpg'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('cname', models.CharField(max_length=200)),
                ('cdate', models.CharField(max_length=20)),
                ('cstime', models.CharField(max_length=20)),
                ('cetime', models.CharField(max_length=20)),
                ('cvenue', models.CharField(max_length=200)),
                ('cfood', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='bookenevent',
        ),
    ]
