# Generated by Django 4.1.2 on 2022-11-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_catering_musicalconcert_weddinghalls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
