# Generated by Django 4.1.2 on 2022-11-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_email_catering_emailmanu_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musicalconcert',
            new_name='Musicalconcertm',
        ),
    ]
