# Generated by Django 4.1.2 on 2022-11-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_musicalconcertm_weddinghalls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
