# Generated by Django 4.1.2 on 2022-11-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='catering',
        ),
        migrations.DeleteModel(
            name='Musicalconcertm',
        ),
        migrations.DeleteModel(
            name='weddinghalls',
        ),
    ]
