# Generated by Django 4.1.2 on 2022-11-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_catering_musicalconcertm_weddinghalls'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
            ],
        ),
    ]
