# Generated by Django 4.1.2 on 2022-11-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact1',
        ),
    ]
