# Generated by Django 4.1.3 on 2022-11-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_contact_contact1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthdayparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('bname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('pcode', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
