# Generated by Django 4.1.3 on 2022-12-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_birthdayparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='dcontact1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
            ],
        ),
    ]
