# Generated by Django 4.1.3 on 2022-12-01 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_dcontact1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dcontact1',
        ),
    ]
