# Generated by Django 4.1.3 on 2022-12-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_dcontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='catering',
        ),
    ]
