# Generated by Django 4.1.3 on 2022-12-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_catering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='catering',
        ),
    ]
