# Generated by Django 4.1.3 on 2022-12-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_delete_catering'),
    ]

    operations = [
        migrations.CreateModel(
            name='catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=200)),
                ('namemanu', models.CharField(max_length=200)),
                ('pricemanu', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('emailmanu', models.CharField(max_length=200)),
            ],
        ),
    ]
