# Generated by Django 4.1.3 on 2022-12-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_catering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthdayParty',
        ),
        migrations.DeleteModel(
            name='Musicalconcertm',
        ),
        migrations.DeleteModel(
            name='weddinghalls',
        ),
    ]
