# Generated by Django 4.1.3 on 2022-12-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_delete_birthdayparty_delete_musicalconcertm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('type3', models.CharField(max_length=200)),
                ('birthdayname', models.CharField(max_length=200)),
                ('birthdayame', models.CharField(max_length=200)),
                ('birthdayAddress', models.CharField(max_length=200)),
                ('birthdayCity', models.CharField(max_length=200)),
                ('birthdaypcode', models.CharField(max_length=200)),
                ('birthdayprice', models.CharField(max_length=200)),
                ('birthdaymobile', models.CharField(max_length=10)),
                ('birthdayemail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Musicalconcertm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('type1', models.CharField(max_length=200)),
                ('conname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('pcode', models.CharField(max_length=200)),
                ('Tprice', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='weddinghalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('type2', models.CharField(max_length=200)),
                ('wname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('pcode', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
