# Generated by Django 4.1.3 on 2022-12-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_birthdayparty_musicalconcertm_weddinghalls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthdayParty',
        ),
        migrations.DeleteModel(
            name='Musicalconcertm',
        ),
        migrations.DeleteModel(
            name='weddinghalls',
        ),
    ]
