# Generated by Django 4.1.2 on 2022-12-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_birthdayparty_musicalconcertm_weddinghalls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
