# Generated by Django 4.1.2 on 2022-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('cname', models.CharField(max_length=200)),
                ('cdate', models.CharField(max_length=20)),
                ('cstime', models.CharField(max_length=20)),
                ('cetime', models.CharField(max_length=20)),
                ('cvenue', models.CharField(max_length=200)),
                ('cfood', models.CharField(max_length=10)),
                ('sdealer', models.CharField(max_length=200)),
            ],
        ),
    ]
