from django.contrib import admin
from django.urls import path
from . import views
urlpatterns =[path('',views.home,name="login"),
              path('home/',views.home,name="home"),
              path('userlogin/',views.userlogin,name='login' ),
              path('userregister/',views.userregister,name='register'),
              path('dealerlogin/',views.dealerlogin,name='login2' ),
              path('dealerregister/',views.dealerregister,name='register2'),
              path('dealerhome/',views.dealerhome,name="dealerhome"),
              path('history/',views.history,name='history'),
              path('dealerhistory/',views.dealerhistory,name='dhistory'),
              path('dealerhistory1/',views.dealerhistory1,name='dhistory1'),
              path('dealerhistory2/',views.dealerhistory2,name='dhistory2'),
              path('dealerhistory3/',views.dealerhistory3,name='dhistory3'),
              path('dealerhistory00/',views.dealerhistory00,name='dhistory00'),
              path('dealerhistory01/',views.dealerhistory01,name='dhistory01'),
              path('dealerhistory02/',views.dealerhistory02,name='dhistory02'),
              path('dealerhistory03/',views.dealerhistory03,name='dhistory03'),
              path('faqs/',views.faqs,name="faqs"),
              path('faqs1/',views.dfaqs,name="dfaqs"),
              path('deleteevent/', views.deleteevent, name="deleteevent"),
              path('contact/',views.contactform,name="contact"),
              path('contact/',views.contact,name="contact"),
              path('contact1/',views.dealercontacts1,name="contact1"),
              path('contact1/',views.dealercontacts,name="contact1"),
              path('about/',views.about,name="about"),
              path('about1/',views.dabout,name="dabout"),
              path('calender/',views.calender,name="calender"),
              path('userregisteruser',views.userregisteruser,name="registeruser"),
              path('userloginuser',views.userloginuser,name="loginuser"),
              path('dealerregisteruser',views.dealerregisteruser,name="registeruser2"),
              path('dealerloginuser',views.dealerloginuser,name="loginuser2"),
              path('event/',views.event1,name="event"),

              path('cateringbook/',views.cateringbook,name="cateringbook"),
              path('Musicbook/',views.Musicbook,name="Musicbook"),
              path('weddingbook/',views.weddingbook,name="weddingbook"),
              path('Birthdaybook/',views.Birthdaybook,name="Birthdaybook"),
              path('weddinghall/',views.weddinghall1,name="weddinghall"),
              path('cateringservice/',views.Caterings,name="cateringservice"),
              path('Musicalconcert/',views.MusicConcerts,name="Musicalconcert"),
              path('birthday/',views.Birthday,name="Birthday"),
              path('loginout/', views.loginout, name="userlogout"),
              path('loginout2/', views.loginout2, name="dealerlogout"),
              path('fp/', views.fp, name="Forgot Password"),
              path('fp1/', views.fp1, name="Fp1"),
              path('cp/', views.cp, name="Change Password"),
              path('cp1/', views.cp1, name="Changing password"),
              path('fp2/', views.fp2, name="Forgot Password"),
              path('fp3/', views.fp3, name="Fp1"),
              path('cp2/', views.cp2, name="Change Password"),
              path('cp3/', views.cp3, name="Changing password")

            
]
